### ISSUE TITLE
Add getrawtransaction to BitcoindApi

### ISSUE THREAD

**Issue by natzei** [SulacoSoft/BitcoindConnector4J#2]
Hi all,
I really like the simplicity of this project, it works well and it is easy to maintain.

For my project, I need to include the method `getrawtransaction`, which returns a string when `getrawtransaction txid [verbose]` is invoked without the optional param or with verbose=false, and a Json object when verbose=true.

In my fork, I added two methods to `BitcoindApi`, i.e.
```java
    String getrawtransaction(String txid);	// (1)
    RawTransaction getrawtransaction(String txid, boolean verbose);   // (2)
```
where `RawTransaction` is a pojo as usual.

Unfortunately,  method `(2)` fails when invoked with verbose=false, because it's returning a String.

Do you have any idea on how to deal with it? I'm available to implement it.

**Comment by sebastiandz** [comment]
Hello Nicola

Theoretically enough to add to the api method:
RawTransaction getrawtransaction(String txid, boolean verbose);

and add implementation in attached file (RawTransaction.java). The method
call will succeed, unfortunately, it will not be possible to read all the
fields.
Please wait a few days and I will provide a fully working solution.

Best wishes,
Sebastian Dziak



2017-09-26 21:49 GMT+02:00 Nicola Atzei <notifications@github.com>:

**Comment by natzei** [comment]
Thank you Sebastian, I'm looking forward to see how you'll implement it.

**Comment by sebastiandz** [comment]
Hello Nicola,

I prepared new version API with implemented methods getrawtransaction. All
changes are on available in github, master branch.
If you find any bug then please write email to me :)

Best wishes,
Sebastian Dziak


2017-09-27 10:06 GMT+02:00 Nicola Atzei <notifications@github.com>:

**Comment by natzei** [comment]
You replaced the json library, thanks! It was really outdated :)
I'll try it tomorrow morning.

Just to not open a new PR, could you please add the method `String sendrawtransaction(String txhex)` to the API? 

Thank you very much!

**Comment by sebastiandz** [comment]
Please create branch with you changes and add merge request, I'll add your
propositions.

2017-09-27 23:18 GMT+02:00 Nicola Atzei <notifications@github.com>:

**Comment by natzei** [comment]
Hi Sebastian,
I've tested your implementation. Unfortunately invoking `getrawtransaction("...", false)` throws an exception:

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.sulacosoft.bitcoindconnector4j.BitcoindApiHandler.invoke(BitcoindApiHandler.java:95)
	at com.sun.proxy.$Proxy8.getrawtransaction(Unknown Source)
...
```

**Comment by natzei** [comment]
See the PR #3. I hope you'll like my solution.

**Comment by sebastiandz** [comment]
Thank you, I merged your changes. Next time add your name to file signature
:)


2017-09-28 11:06 GMT+02:00 Nicola Atzei <notifications@github.com>:
